[env:seeed_xiao_esp32c6]
platform = espressif32@6.12.0
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
upload_protocol = esptool

; Seeed XIAO ESP32-C6 is a 4 MB flash board.
board_upload.flash_size = 4MB
board_build.partitions = partitions_singleapp_large.csv

build_flags =
  -Wall
  -Wextra
